# Generated by Django 5.0.4 on 2024-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_disease_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.JSONField(default='null'),
        ),
    ]
