# Generated by Django 5.0.4 on 2024-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_alter_disease_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='medicines',
            field=models.JSONField(default='null'),
        ),
    ]
