# Generated by Django 5.0.4 on 2024-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_alter_disease_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='medicines',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.JSONField(),
        ),
    ]
