# Generated by Django 5.0.4 on 2024-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_alter_disease_medicines_alter_disease_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='medicines',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(),
        ),
    ]
