# Generated by Django 5.0.4 on 2024-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_alter_disease_medicines_alter_disease_prevention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='prevention',
            new_name='precautions',
        ),
    ]
