# Generated by Django 5.0.4 on 2024-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0012_alter_disease_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medicines',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='precautions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
